### ISSUE TITLE
The demo-oai-hss of EPC  is always disconnected 

### ISSUE THREAD

**Issue by XXK777** [OPENAIRINTERFACE/openair-epc-fed#26]
Hellow everyone !
There has some questions for me , The demo-oai-hss is disconnected when I run this command :demo-compose up -d oai_spgwu.the logs of demo-oai-hss  see there:

pc@pc:~/openair-epc-fed/docker-compose/magma-mme-demo$ docker logs demo-oai-hss
/openair-hss/scripts /openair-hss
wait-for-it.sh: waiting 15 seconds for 192.168.68.130:9042
wait-for-it.sh: 192.168.68.130:9042 is available after 0 seconds
Traceback (most recent call last):
  File "./data_provisioning_users", line 216, in <module>
    main()
...........................................................................
 File "/usr/lib/python3/dist-packages/cassandra/cluster.py", line 1998, in execute
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
  File "/usr/lib/python3/dist-packages/cassandra/cluster.py", line 3781, in result
    raise self._final_exception
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace vhss does not exist"

Thank for your answer very  much !    ：）  ：）  ：）

**Comment by Harsihv** [comment]
@XXK777 Have you solved this issue
